name: Automated tests

on:
  pull_request:
    branches:
      "main"
  push:
    branches:
      "main"

jobs:
  runTests:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - uses: browser-actions/setup-chrome@v1
        - name: Build with Maven
          run: mvn -B package --file testng.xml
        - name: Copy history
          uses: actions/checkout@v3
          if: always()
          with:
            ref: gh-pages
            path: gh-pages
        - name: Build Allure Report
          uses: simple-elf/allure-report-action@master
          if: always()
          with:
            allure_results: build/allure-results
            allure_history: allure-history
            keep_reports: 20
        - name: Allure Report
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history

        # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
        - name: Update dependency graph
          uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6